In [1]:
import numpy as np

# Initial variables
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <U1


In [2]:
import numpy as np

# Initial variables
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
import numpy as np

# Initial variables
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
array_list_int = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(element.dtype)

# Print data types of elements in array_list_int
print("Data types of elements in array_list_int:")
for element in array_list_int:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1
Data types of elements in array_list_int:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
import numpy as np

# Create num_array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
import numpy as np

# Create a 3x3 matrix with zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print("3x3 matrix of zeros:")
print(zero_matrix)


3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
